export const API = {
  baseURL: "https://ub.app.techdatasoft.uz/api/v1/",
  baseURL_IMAGE: "https://ub.app.techdatasoft.uz/uploads/images/",
};

export const arrayCreator = (count = 1) =>
  Array.from({ length: count }, (_, i) => i);

export const skeletionData = {
  slider: arrayCreator(5),
  categories: arrayCreator(10),
};

const formatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "UZS",
  minimumFractionDigits: 0, // (this suffices for whole numbers, but will print 2500.10 as $2,500.1)
  maximumFractionDigits: 0, // (causes 2500.99 to be printed as $2,501)
});

export const currencyString = (string = "") =>
  formatter.format(string).split("UZS")[1]?.trim()?.replaceAll(",", " ") +
  " " +
  formatter.resolvedOptions().currency;

export const isSelectedProduct = (product, arrayList) =>
  arrayList.find((ident) => {
    if (typeof ident === "object") {
      return ident?.seo === product?.seo;
    } else return ident === product?.seo;
  });

export const removeDuplicates = (arr) => [...new Set(arr)];

function getVideoId(url) {
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
  const match = url?.match(regExp);

  return match && match[2].length === 11 ? match[2] : null;
}

export const youtubeEmbed = (url) =>
  "https://www.youtube.com/embed/" + getVideoId(url);

export const goContact = () => {
  const element = document.getElementById("contact-form");
  if (element) {
    element?.scrollIntoView({ behavior: "smooth" });
    setTimeout(() => {
      element?.children[2]?.click();
    }, 500);
  }
};

export const countries = [
  /*     {
          code: 1726,
          name: "Tashkent city",
          nameUzCyrl: "Тошкент шаҳри",
          nameUzLatn: "Toshkent shahri",
          nameRu: "город Ташкент",
          regionId: 26,
          districtsId: 0,
          active: 1,
        }, */
  {
    code: 1727,
    name: "Tashkent region",
    nameUzCyrl: "Тошкент вилояти",
    nameUzLatn: "Toshkent viloyati",
    nameRu: "Ташкентская область",
    regionId: 27,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1703,
    name: "Andijan region",
    nameUzCyrl: "Андижон вилояти",
    nameUzLatn: "Andijon viloyati",
    nameRu: "Андижанская область",
    regionId: 3,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1706,
    name: "Bukhara region",
    nameUzCyrl: "Бухоро вилояти",
    nameUzLatn: "Buxoro viloyati",
    nameRu: "Бухарская область",
    regionId: 6,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1714,
    name: "Namangan region",
    nameUzCyrl: "Наманган вилояти",
    nameUzLatn: "Namangan viloyati",
    nameRu: "Наманганская область",
    regionId: 14,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1730,
    name: "Fergana region",
    nameUzCyrl: "Фарғона вилояти",
    nameUzLatn: "Farg'ona viloyati",
    nameRu: "Ферганская область",
    regionId: 30,
    districtsId: 0,
    active: 1,
  },

  {
    code: 1733,
    name: "Khorezm region",
    nameUzCyrl: "Хоразм вилояти",
    nameUzLatn: "Xorazm viloyati",
    nameRu: "Хорезмская область",
    regionId: 33,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1724,
    name: "Syrdarya region",
    nameUzCyrl: "Сирдарё вилояти",
    nameUzLatn: "Sirdaryo viloyati",
    nameRu: "Сырдарьинская область",
    regionId: 24,
    districtsId: 0,
    active: 1,
  },

  {
    code: 1710,
    name: "Kashkadarya region",
    nameUzCyrl: "Қашқадарё вилояти",
    nameUzLatn: "Qashqadaryo viloyati",
    nameRu: "Кашкадарьинская область",
    regionId: 10,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1712,
    name: "Navoi region",
    nameUzCyrl: "Навоий вилояти",
    nameUzLatn: "Navoiy viloyati",
    nameRu: "Навоийская область",
    regionId: 12,
    districtsId: 0,
    active: 1,
  },

  {
    code: 1718,
    name: "Samarkand region",
    nameUzCyrl: "Самарқанд вилояти",
    nameUzLatn: "Samarqand viloyati",
    nameRu: "Самаркандская область",
    regionId: 18,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1722,
    name: "Surkhandarya region",
    nameUzCyrl: "Сурхондарё вилояти",
    nameUzLatn: "Surxondaryo viloyati",
    nameRu: "Сурхандарьинская область",
    regionId: 22,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1708,
    name: "Jizzakh region",
    nameUzCyrl: "Жиззах вилояти",
    nameUzLatn: "Jizzax viloyati",
    nameRu: "Джизакская область",
    regionId: 8,
    districtsId: 0,
    active: 1,
  },
  {
    code: 1735,
    name: "Republic of Karakalpakstan",
    nameUzCyrl: "Қорақалпоғистон Республикаси",
    nameUzLatn: "Qoraqalpog'iston Respublikasi",
    nameRu: "Республика Каракалпакстан",
    regionId: 35,
    districtsId: 0,
    active: 1,
  },

  // {
  //   code: 1750,
  //   name: "Xududlararo inspeksiya",
  //   nameUzCyrl: "Ҳудудлараро инспекция",
  //   nameUzLatn: "Xududlararo inspeksiya",
  //   nameRu: "МРИ",
  //   regionId: 50,
  //   districtsId: 1,
  //   active: 1,
  // },
];

export const regions = [
  {
    code: 1730230,
    name: "Uzbekistan region",
    nameUzCyrl: "Ўзбекистон тумани",
    nameUzLatn: "O'zbekiston tumani",
    nameRu: "Узбекистанский район",
    regionId: 30,
    districtsId: 17,
    active: 1,
  },
  {
    code: 1730233,
    name: "Fergana region",
    nameUzCyrl: "Фарғона тумани",
    nameUzLatn: "Farg'ona tumani",
    nameRu: "Ферганский район",
    regionId: 30,
    districtsId: 19,
    active: 1,
  },
  {
    code: 1730236,
    name: "Dangara district",
    nameUzCyrl: "Данғара тумани",
    nameUzLatn: "Dang'ara tumani",
    nameRu: "Дангаринский район",
    regionId: 30,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1730203,
    name: "Altyaryk district",
    nameUzCyrl: "Олтиариқ тумани",
    nameUzLatn: "Oltiariq tumani",
    nameRu: "Алтыарыкский район",
    regionId: 30,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1730206,
    name: "Kushtepa district",
    nameUzCyrl: "Қўштепа тумани",
    nameUzLatn: "Qo'shtepa tumani",
    nameRu: "Куштепинский район",
    regionId: 30,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1730209,
    name: "Baghdad region",
    nameUzCyrl: "Боғдод тумани",
    nameUzLatn: "Bog'dod tumani",
    nameRu: "Багдадский район",
    regionId: 30,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1730212,
    name: "Buvaida district",
    nameUzCyrl: "Бувайда тумани",
    nameUzLatn: "Buvayda tumani",
    nameRu: "Бувайдинский район",
    regionId: 30,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1730215,
    name: "Besharyk region",
    nameUzCyrl: "Бешариқ тумани",
    nameUzLatn: "Beshariq tumani",
    nameRu: "Бешарыкский район",
    regionId: 30,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1730218,
    name: "Kuva district",
    nameUzCyrl: "Қува тумани",
    nameUzLatn: "Quva tumani",
    nameRu: "Кувинский район",
    regionId: 30,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1730221,
    name: "Uchkuprik district",
    nameUzCyrl: "Учкўприк тумани",
    nameUzLatn: "Uchko'prik tumani",
    nameRu: "Учкуприкский район",
    regionId: 30,
    districtsId: 18,
    active: 1,
  },
  {
    code: 1730224,
    name: "Rishtan region",
    nameUzCyrl: "Риштон тумани",
    nameUzLatn: "Rishton tumani",
    nameRu: "Риштанский район",
    regionId: 30,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1730226,
    name: "Sokh district",
    nameUzCyrl: "Сўх тумани",
    nameUzLatn: "So'x tumani",
    nameRu: "Сохский район",
    regionId: 30,
    districtsId: 15,
    active: 1,
  },
  {
    code: 1730227,
    name: "Tashlak region",
    nameUzCyrl: "Тошлоқ тумани",
    nameUzLatn: "Toshloq tumani",
    nameRu: "Ташлакский район",
    regionId: 30,
    districtsId: 16,
    active: 1,
  },
  {
    code: 1730238,
    name: "Furkat district",
    nameUzCyrl: "Фурқат тумани",
    nameUzLatn: "Furqat tumani",
    nameRu: "Фуркатский район",
    regionId: 30,
    districtsId: 20,
    active: 1,
  },
  {
    code: 1730242,
    name: "Yazyavan region",
    nameUzCyrl: "Ёзёвон тумани",
    nameUzLatn: "Yozyovon tumani",
    nameRu: "Язъяванский район",
    regionId: 30,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1730401,
    name: "Fergana",
    nameUzCyrl: "Фарғона шаҳар",
    nameUzLatn: "Farg‘ona shahar",
    nameRu: "город Фергана",
    regionId: 30,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1730405,
    name: "Kokand",
    nameUzCyrl: "Қўқон шаҳар",
    nameUzLatn: "Qo‘qon shahar",
    nameRu: "город Коканд",
    regionId: 30,
    districtsId: 3,
    active: 1,
  },
  {
    code: 1730408,
    name: "Kuvasay",
    nameUzCyrl: "Қувасой шаҳар",
    nameUzLatn: "Quvasoy shahar",
    nameRu: "город Кувасай",
    regionId: 30,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1730412,
    name: "Margilan",
    nameUzCyrl: "Марғилон шаҳар",
    nameUzLatn: "Marg‘ilon shahar",
    nameRu: "город Маргилан",
    regionId: 30,
    districtsId: 4,
    active: 1,
  },

  {
    code: 1735204,
    name: "Amudarya region",
    nameUzCyrl: "Амударё тумани",
    nameUzLatn: "Amudaryo tumani",
    nameRu: "Амударьинский район",
    regionId: 35,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1735207,
    name: "Beruni district",
    nameUzCyrl: "Беруний тумани",
    nameUzLatn: "Beruniy tumani",
    nameRu: "Берунийский район",
    regionId: 35,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1735209,
    name: "Bozatausky district",
    nameUzCyrl: "Бўзатов тумани",
    nameUzLatn: "Bo'zatov tumani",
    nameRu: "Бозатауский район",
    regionId: 35,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1735211,
    name: "Karauzyak district",
    nameUzCyrl: "Қораўзак тумани",
    nameUzLatn: "Qorao'zak tumani",
    nameRu: "Караузякский район",
    regionId: 35,
    districtsId: 22,
    active: 1,
  },
  {
    code: 1735212,
    name: "Kegeyli region",
    nameUzCyrl: "Кегейли тумани",
    nameUzLatn: "Kegeyli tumani",
    nameRu: "Кегейлийский район",
    regionId: 35,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1735215,
    name: "Kungradsky district",
    nameUzCyrl: "Қўнғирот тумани",
    nameUzLatn: "Qo'ng'irot tumani",
    nameRu: "Кунградский район",
    regionId: 35,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1735218,
    name: "Kanlykul district",
    nameUzCyrl: "Қанликўл тумани",
    nameUzLatn: "Qanliko'l tumani",
    nameRu: "Канлыкульский район",
    regionId: 35,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1735222,
    name: "Muynak district",
    nameUzCyrl: "Мўйноқ тумани",
    nameUzLatn: "Mo'ynoq tumani",
    nameRu: "Муйнакский район",
    regionId: 35,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1735225,
    name: "Nukus region",
    nameUzCyrl: "Нукус тумани",
    nameUzLatn: "Nukus tumani",
    nameRu: "Нукусский район",
    regionId: 35,
    districtsId: 15,
    active: 1,
  },
  {
    code: 1735228,
    name: "Takhiatash district",
    nameUzCyrl: "Тахиатош тумани",
    nameUzLatn: "Taxiatosh tumani",
    nameRu: "Тахиаташский район",
    regionId: 35,
    districtsId: 23,
    active: 1,
  },
  {
    code: 1735230,
    name: "Takhtakupyr district",
    nameUzCyrl: "Тахтакўпир тумани",
    nameUzLatn: "Taxtako'pir tumani",
    nameRu: "Тахтакупырский район",
    regionId: 35,
    districtsId: 16,
    active: 1,
  },
  {
    code: 1735233,
    name: "Turtkul district",
    nameUzCyrl: "Тўрткўл тумани",
    nameUzLatn: "To'rtko'l tumani",
    nameRu: "Турткульский район",
    regionId: 35,
    districtsId: 17,
    active: 1,
  },
  {
    code: 1735236,
    name: "Khodjeyli region",
    nameUzCyrl: "Хўжайли тумани",
    nameUzLatn: "Xo'jayli tumani",
    nameRu: "Ходжейлийский район",
    regionId: 35,
    districtsId: 18,
    active: 1,
  },
  {
    code: 1735240,
    name: "Chimbay region",
    nameUzCyrl: "Чимбой тумани",
    nameUzLatn: "Chimboy tumani",
    nameRu: "Чимбайский район",
    regionId: 35,
    districtsId: 19,
    active: 1,
  },
  {
    code: 1735243,
    name: "Shumanay region",
    nameUzCyrl: "Шуманай тумани",
    nameUzLatn: "Shumanay tumani",
    nameRu: "Шуманайский район",
    regionId: 35,
    districtsId: 20,
    active: 1,
  },
  {
    code: 1735250,
    name: "Ellikkala region",
    nameUzCyrl: "Елликкала тумани",
    nameUzLatn: "Ellikkala tumani",
    nameRu: "Элликкалинский район",
    regionId: 35,
    districtsId: 21,
    active: 1,
  },
  {
    code: 1735401,
    name: "Nukus",
    nameUzCyrl: "Нукус шаҳар",
    nameUzLatn: "Nukus shahar",
    nameRu: "город Нукус",
    regionId: 35,
    districtsId: 1,
    active: 1,
  },

  {
    code: 1726262,
    name: "Uchtepa district",
    nameUzCyrl: "Учтепа тумани",
    nameUzLatn: "Uchtepa tumani",
    nameRu: "Учтепинский район",
    regionId: 26,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1726264,
    name: "Bektemir district",
    nameUzCyrl: "Бектемир тумани",
    nameUzLatn: "Bektemir tumani",
    nameRu: "Бектемирский район",
    regionId: 26,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1726266,
    name: "Yunusabad district",
    nameUzCyrl: "Юнусобод тумани",
    nameUzLatn: "Yunusobod tumani",
    nameRu: "Юнусабадский район",
    regionId: 26,
    districtsId: 3,
    active: 1,
  },
  {
    code: 1726269,
    name: "Mirzo-Ulugbek district",
    nameUzCyrl: "Мирзо Улуғбек тумани",
    nameUzLatn: "Mirzo Ulug'bek tumani",
    nameRu: "Мирзо-Улугбекский район",
    regionId: 26,
    districtsId: 2,
    active: 1,
  },
  {
    code: 1726273,
    name: "Mirabad district",
    nameUzCyrl: "Миробод тумани",
    nameUzLatn: "Mirobod tumani",
    nameRu: "Мирабадский район",
    regionId: 26,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1726277,
    name: "Shaykhantakhur district",
    nameUzCyrl: "Шайхонтохур тумани",
    nameUzLatn: "Shayxontoxur tumani",
    nameRu: "Шайхантахурский район",
    regionId: 26,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1726280,
    name: "Almazar district",
    nameUzCyrl: "Олмазор тумани",
    nameUzLatn: "Olmazor tumani",
    nameRu: "Алмазарский район",
    regionId: 26,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1726283,
    name: "Sergeli district",
    nameUzCyrl: "Сирғали тумани",
    nameUzLatn: "Sirg'ali tumani",
    nameRu: "Сергелийский район",
    regionId: 26,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1726287,
    name: "Yakkasaray district",
    nameUzCyrl: "Яккасарой тумани",
    nameUzLatn: "Yakkasaroy tumani",
    nameRu: "Яккасарайский район",
    regionId: 26,
    districtsId: 4,
    active: 1,
  },
  {
    code: 1726290,
    name: "Yashnobodsky district",
    nameUzCyrl: "Яшнобод тумани",
    nameUzLatn: "Yashnobod tumani",
    nameRu: "Яшнободский район",
    regionId: 26,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1726292,
    name: "Yangihayot tumani",
    nameUzCyrl: "Янгихаёт райони",
    nameUzLatn: "Yangihayot tumani",
    nameRu: "Янгихаётский район",
    regionId: 26,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1726294,
    name: "Chilanzar region",
    nameUzCyrl: "Чилонзор тумани",
    nameUzLatn: "Chilonzor tumani",
    nameRu: "Чиланзарский район",
    regionId: 26,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1624251,
    name: "Tashkent city",
    nameUzCyrl: "Тошкент шаҳри",
    nameUzLatn: "Toshkent shahri",
    nameRu: "город Ташкент",
    regionId: 27,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1727250,
    name: "Pskent region",
    nameUzCyrl: "Пскент тумани",
    nameUzLatn: "Pskent tumani",
    nameRu: "Пскентский район",
    regionId: 27,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1727253,
    name: "Urtachirchik district",
    nameUzCyrl: "Ўртачирчиқ тумани",
    nameUzLatn: "O'rtachirchiq tumani",
    nameRu: "Уртачирчикский район",
    regionId: 27,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1727256,
    name: "Chinaz district",
    nameUzCyrl: "Чиноз тумани",
    nameUzLatn: "Chinoz tumani",
    nameRu: "Чиназский район",
    regionId: 27,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1727259,
    name: "Yangiyul district",
    nameUzCyrl: "Янгиёъл тумани",
    nameUzLatn: "Yangiyo'l tumani",
    nameRu: "Янгиюльский район",
    regionId: 27,
    districtsId: 15,
    active: 1,
  },
  {
    code: 1727265,
    name: "Tashkent region",
    nameUzCyrl: "Тошкент тумани",
    nameUzLatn: "Toshkent tumani",
    nameRu: "Ташкентский район",
    regionId: 27,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1727401,
    name: "Nurafshon",
    nameUzCyrl: "Нурафшон шаҳар",
    nameUzLatn: "Nurafshon shahar",
    nameRu: "город Нурафшон",
    regionId: 27,
    districtsId: 23,
    active: 1,
  },
  {
    code: 1727404,
    name: "Almalyk",
    nameUzCyrl: "Олмалиқ шаҳар",
    nameUzLatn: "Olmaliq shahar",
    nameRu: "город Алмалык",
    regionId: 27,
    districtsId: 18,
    active: 1,
  },
  {
    code: 1727407,
    name: "Angren",
    nameUzCyrl: "Ангрен шаҳар",
    nameUzLatn: "Angren shahar",
    nameRu: "город Ангрен",
    regionId: 27,
    districtsId: 16,
    active: 1,
  },
  {
    code: 1727413,
    name: "Bekabad",
    nameUzCyrl: "Бекобод шаҳар",
    nameUzLatn: "Bekobod shahar",
    nameRu: "город Бекабад",
    regionId: 27,
    districtsId: 17,
    active: 1,
  },
  {
    code: 1727415,
    name: "Akhangaran",
    nameUzCyrl: "Оҳангарон шаҳар",
    nameUzLatn: "Ohangaron shahar",
    nameRu: "город Ахангаран",
    regionId: 27,
    districtsId: 19,
    active: 1,
  },
  {
    code: 1727419,
    name: "Chirchik",
    nameUzCyrl: "Чирчиқ шаҳар",
    nameUzLatn: "Chirchiq shahar",
    nameRu: "город Чирчик",
    regionId: 27,
    districtsId: 20,
    active: 1,
  },
  {
    code: 1727424,
    name: "Yangiyul",
    nameUzCyrl: "Янгийўл шаҳар",
    nameUzLatn: "Yangiyo‘l shahar",
    nameRu: "город Янгийуль",
    regionId: 27,
    districtsId: 22,
    active: 1,
  },
  {
    code: 1727206,
    name: "Akkurgan region",
    nameUzCyrl: "Оққўрғон тумани",
    nameUzLatn: "Oqqo'rg'on tumani",
    nameRu: "Аккурганский район",
    regionId: 27,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1727212,
    name: "Akhangaran region",
    nameUzCyrl: "Оҳангарон тумани",
    nameUzLatn: "Ohangaron tumani",
    nameRu: "Ахангаранский район",
    regionId: 27,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1727220,
    name: "Bekabad region",
    nameUzCyrl: "Бекобод тумани",
    nameUzLatn: "Bekobod tumani",
    nameRu: "Бекабадский район",
    regionId: 27,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1727224,
    name: "Bostanlyk region",
    nameUzCyrl: "Бўстонлиқ тумани",
    nameUzLatn: "Bo'stonliq tumani",
    nameRu: "Бостанлыкский район",
    regionId: 27,
    districtsId: 3,
    active: 1,
  },
  {
    code: 1727228,
    name: "Bukinsky district",
    nameUzCyrl: "Бўка тумани",
    nameUzLatn: "Bo'ka tumani",
    nameRu: "Букинский район",
    regionId: 27,
    districtsId: 2,
    active: 1,
  },
  {
    code: 1727233,
    name: "Kuyichirchik district",
    nameUzCyrl: "Қийичирчиқ тумани",
    nameUzLatn: "Qiyichirchiq tumani",
    nameRu: "Куйичирчикский район",
    regionId: 27,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1727237,
    name: "Zangiata region",
    nameUzCyrl: "Зангиота тумани",
    nameUzLatn: "Zangiota tumani",
    nameRu: "Зангиатинский район",
    regionId: 27,
    districtsId: 4,
    active: 1,
  },
  {
    code: 1727239,
    name: "Yukorichirchik district",
    nameUzCyrl: "Юқоричирчиқ тумани",
    nameUzLatn: "Yuqorichirchiq tumani",
    nameRu: "Юкоричирчикский район",
    regionId: 27,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1727248,
    name: "Kibray district",
    nameUzCyrl: "Қибрай тумани",
    nameUzLatn: "Qibray tumani",
    nameRu: "Кибрайский район",
    regionId: 27,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1727249,
    name: "Parkent district",
    nameUzCyrl: "Паркент тумани",
    nameUzLatn: "Parkent tumani",
    nameRu: "Паркентский район",
    regionId: 27,
    districtsId: 9,
    active: 1,
  },

  {
    code: 1733226,
    name: "Khiva district",
    nameUzCyrl: "Хива тумани",
    nameUzLatn: "Xiva tumani",
    nameRu: "Хивинский район",
    regionId: 33,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1733230,
    name: "Shavat region",
    nameUzCyrl: "Шовот тумани",
    nameUzLatn: "Shovot tumani",
    nameRu: "Шаватский район",
    regionId: 33,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1733233,
    name: "Yangiarik district",
    nameUzCyrl: "Янгиариқ тумани",
    nameUzLatn: "Yangiariq tumani",
    nameRu: "Янгиарыкский район",
    regionId: 33,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1733236,
    name: "Yangibazar district",
    nameUzCyrl: "Янгибозор тумани",
    nameUzLatn: "Yangibozor tumani",
    nameRu: "Янгибазарский район",
    regionId: 33,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1733401,
    name: "Urgench",
    nameUzCyrl: "Урганч шаҳар",
    nameUzLatn: "Urganch shahar",
    nameRu: "город Ургенч",
    regionId: 33,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1733406,
    name: "Khiva",
    nameUzCyrl: "Хива шаҳар",
    nameUzLatn: "Xiva shahar",
    nameRu: "город Хива",
    regionId: 33,
    districtsId: 2,
    active: 1,
  },
  {
    code: 1733204,
    name: "Bagat district",
    nameUzCyrl: "Боғот тумани",
    nameUzLatn: "Bog'ot tumani",
    nameRu: "Багатский район",
    regionId: 33,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1733208,
    name: "Gurlensky district",
    nameUzCyrl: "Гурлан тумани",
    nameUzLatn: "Gurlan tumani",
    nameRu: "Гурленский район",
    regionId: 33,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1733212,
    name: "Koshkupir district",
    nameUzCyrl: "Қўшкўпир тумани",
    nameUzLatn: "Qo'shko'pir tumani",
    nameRu: "Кошкупырский район",
    regionId: 33,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1733217,
    name: "Urgench district",
    nameUzCyrl: "Урганч тумани",
    nameUzLatn: "Urganch tumani",
    nameRu: "Ургенчский район",
    regionId: 33,
    districtsId: 4,
    active: 1,
  },
  {
    code: 1733220,
    name: "Khazarasp district",
    nameUzCyrl: "Хазорасп тумани",
    nameUzLatn: "Xazorasp tumani",
    nameRu: "Хазараспский район",
    regionId: 33,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1733221,
    name: "Tuprokkala region",
    nameUzCyrl: "Тупроққалъа тумани",
    nameUzLatn: "Tuproqqal'a tumani",
    nameRu: "Тупроккалинский район",
    regionId: 33,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1733223,
    name: "Hankinsky district",
    nameUzCyrl: "Хонқа тумани",
    nameUzLatn: "Xonqa tumani",
    nameRu: "Ханкинский район",
    regionId: 33,
    districtsId: 12,
    active: 1,
  },

  {
    code: 1724226,
    name: "Sardob region",
    nameUzCyrl: "Сардоба тумани",
    nameUzLatn: "Sardoba tumani",
    nameRu: "Сардобский район",
    regionId: 24,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1724228,
    name: "Mirzaabad region",
    nameUzCyrl: "Мирзаобод тумани",
    nameUzLatn: "Mirzaobod tumani",
    nameRu: "Мирзаабадский район",
    regionId: 24,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1724231,
    name: "Syrdarya region",
    nameUzCyrl: "Сирдарё тумани",
    nameUzLatn: "Sirdaryo tumani",
    nameRu: "Сырдарьинский район",
    regionId: 24,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1724235,
    name: "Khavassky district",
    nameUzCyrl: "Ховос тумани",
    nameUzLatn: "Xovos tumani",
    nameRu: "Хавасский район",
    regionId: 24,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1724401,
    name: "Golestan",
    nameUzCyrl: "Гулистон шаҳар",
    nameUzLatn: "Guliston shahar",
    nameRu: "город Гулистан",
    regionId: 24,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1724410,
    name: "Shirin",
    nameUzCyrl: "Ширин шаҳар",
    nameUzLatn: "Shirin shahar",
    nameRu: "город Ширин",
    regionId: 24,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1724413,
    name: "Yangier",
    nameUzCyrl: "Янгиер шаҳар",
    nameUzLatn: "Yangier shahar",
    nameRu: "город Янгиер",
    regionId: 24,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1724206,
    name: "Akaltyn district",
    nameUzCyrl: "Оқолтин тумани",
    nameUzLatn: "Oqoltin tumani",
    nameRu: "Акалтынский район",
    regionId: 24,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1724212,
    name: "Bayaut district",
    nameUzCyrl: "Боёвут тумани",
    nameUzLatn: "Boyovut tumani",
    nameRu: "Баяутский район",
    regionId: 24,
    districtsId: 2,
    active: 1,
  },
  {
    code: 1724216,
    name: "Saykhunabad region",
    nameUzCyrl: "Сайхунобод тумани",
    nameUzLatn: "Sayxunobod tumani",
    nameRu: "Сайхунабадский район",
    regionId: 24,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1724220,
    name: "Gulistan region",
    nameUzCyrl: "Гулистон тумани",
    nameUzLatn: "Guliston tumani",
    nameRu: "Гулистанский район",
    regionId: 24,
    districtsId: 3,
    active: 1,
  },

  {
    code: 1703202,
    name: "Altynkul district",
    nameUzCyrl: "Олтинкўл тумани",
    nameUzLatn: "Oltinko'l tumani",
    nameRu: "Алтынкульский район",
    regionId: 3,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1703203,
    name: "Andijan region",
    nameUzCyrl: "Андижон тумани",
    nameUzLatn: "Andijon tumani",
    nameRu: "Андижанский район",
    regionId: 3,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1703206,
    name: "Balykchy region",
    nameUzCyrl: "Балиқчи тумани",
    nameUzLatn: "Baliqchi tumani",
    nameRu: "Балыкчинский район",
    regionId: 3,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1703209,
    name: "Buston district",
    nameUzCyrl: "Бўстон тумани",
    nameUzLatn: "Bo'ston tumani",
    nameRu: "Бустонский район",
    regionId: 3,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1703210,
    name: "Bulakbashinsky district",
    nameUzCyrl: "Булоқбоши тумани",
    nameUzLatn: "Buloqboshi tumani",
    nameRu: "Булакбашинский район",
    regionId: 3,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1703211,
    name: "Zhalakuduk district",
    nameUzCyrl: "Жалақудуқ тумани",
    nameUzLatn: "Jalaquduq tumani",
    nameRu: "Жалакудукский район",
    regionId: 3,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1703214,
    name: "Izbaskan district",
    nameUzCyrl: "Избоскан тумани",
    nameUzLatn: "Izboskan tumani",
    nameRu: "Избасканский район",
    regionId: 3,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1703217,
    name: "Ulugnorsky district",
    nameUzCyrl: "Улуғнор тумани",
    nameUzLatn: "Ulug'nor tumani",
    nameRu: "Улугнорский район",
    regionId: 3,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1703220,
    name: "Kurgantepa district",
    nameUzCyrl: "Қўрғонтепа тумани",
    nameUzLatn: "Qo'rg'ontepa tumani",
    nameRu: "Кургантепинский район",
    regionId: 3,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1703224,
    name: "Asaka district",
    nameUzCyrl: "Асака тумани",
    nameUzLatn: "Asaka tumani",
    nameRu: "Асакинский район",
    regionId: 3,
    districtsId: 15,
    active: 1,
  },
  {
    code: 1703227,
    name: "Markhamat district",
    nameUzCyrl: "Мархамат тумани",
    nameUzLatn: "Marxamat tumani",
    nameRu: "Мархаматский район",
    regionId: 3,
    districtsId: 16,
    active: 1,
  },
  {
    code: 1703230,
    name: "Shakhrikhan district",
    nameUzCyrl: "Шахрихон тумани",
    nameUzLatn: "Shaxrixon tumani",
    nameRu: "Шахриханский район",
    regionId: 3,
    districtsId: 17,
    active: 1,
  },
  {
    code: 1703232,
    name: "Pakhtaabad district",
    nameUzCyrl: "Пахтаобод тумани",
    nameUzLatn: "Paxtaobod tumani",
    nameRu: "Пахтаабадский район",
    regionId: 3,
    districtsId: 18,
    active: 1,
  },
  {
    code: 1703236,
    name: "Khojaabad region",
    nameUzCyrl: "Хўжаобод тумани",
    nameUzLatn: "Xo'jaobod tumani",
    nameRu: "Ходжаабадский район",
    regionId: 3,
    districtsId: 19,
    active: 1,
  },
  {
    code: 1703401,
    name: "Andijan",
    nameUzCyrl: "Андижон шаҳар",
    nameUzLatn: "Andijon shahar",
    nameRu: "город Андижан",
    regionId: 3,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1703408,
    name: "Khanabad",
    nameUzCyrl: "Хонобод шаҳар",
    nameUzLatn: "Xonobod shahar",
    nameRu: "город Ханабад",
    regionId: 3,
    districtsId: 3,
    active: 1,
  },

  {
    code: 1706204,
    name: "Alat region",
    nameUzCyrl: "Олот тумани",
    nameUzLatn: "Olot tumani",
    nameRu: "Алатский район",
    regionId: 6,
    districtsId: 4,
    active: 1,
  },
  {
    code: 1706207,
    name: "Bukhara region",
    nameUzCyrl: "Бухоро тумани",
    nameUzLatn: "Buxoro tumani",
    nameRu: "Бухарский район",
    regionId: 6,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1706212,
    name: "Vabkent region",
    nameUzCyrl: "Вобкент тумани",
    nameUzLatn: "Vobkent tumani",
    nameRu: "Вабкентский район",
    regionId: 6,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1706215,
    name: "Gijduvan region",
    nameUzCyrl: "Ғиждувон тумани",
    nameUzLatn: "G'ijduvon tumani",
    nameRu: "Гиждуванский район",
    regionId: 6,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1706219,
    name: "Kagansky District",
    nameUzCyrl: "Когон тумани",
    nameUzLatn: "Kogon tumani",
    nameRu: "Каганский район",
    regionId: 6,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1706230,
    name: "Karakul region",
    nameUzCyrl: "Қоракўл тумани",
    nameUzLatn: "Qorako'l tumani",
    nameRu: "Каракульский район",
    regionId: 6,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1706232,
    name: "Karaulbazar district",
    nameUzCyrl: "Қоровулбозор тумани",
    nameUzLatn: "Qorovulbozor tumani",
    nameRu: "Караулбазарский район",
    regionId: 6,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1706240,
    name: "Peshkunsky district",
    nameUzCyrl: "Пешку тумани",
    nameUzLatn: "Peshku tumani",
    nameRu: "Пешкунский район",
    regionId: 6,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1706242,
    name: "Romitan region",
    nameUzCyrl: "Ромитан тумани",
    nameUzLatn: "Romitan tumani",
    nameRu: "Ромитанский район",
    regionId: 6,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1706246,
    name: "Zhondor district",
    nameUzCyrl: "Жондор тумани",
    nameUzLatn: "Jondor tumani",
    nameRu: "Жондорский район",
    regionId: 6,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1706258,
    name: "Shafirkan region",
    nameUzCyrl: "Шофиркон тумани",
    nameUzLatn: "Shofirkon tumani",
    nameRu: "Шафирканский район",
    regionId: 6,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1706401,
    name: "Bukhara",
    nameUzCyrl: "Бухоро шаҳар",
    nameUzLatn: "Buxoro shahar",
    nameRu: "город Бухара",
    regionId: 6,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1706403,
    name: "Kagan",
    nameUzCyrl: "Когон шаҳар",
    nameUzLatn: "Kogon shahar",
    nameRu: "город Каган",
    regionId: 6,
    districtsId: 3,
    active: 1,
  },

  {
    code: 1710207,
    name: "Guzar region",
    nameUzCyrl: "Ғузор тумани",
    nameUzLatn: "G'uzor tumani",
    nameRu: "Гузарский район",
    regionId: 10,
    districtsId: 4,
    active: 1,
  },
  {
    code: 1710212,
    name: "Dehkanabad region",
    nameUzCyrl: "Деҳқонобод тумани",
    nameUzLatn: "Dehqonobod tumani",
    nameRu: "Дехканабадский район",
    regionId: 10,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1710220,
    name: "Kamashinsky district",
    nameUzCyrl: "Қамаши тумани",
    nameUzLatn: "Qamashi tumani",
    nameRu: "Камашинский район",
    regionId: 10,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1710224,
    name: "Karshi region",
    nameUzCyrl: "Қарши тумани",
    nameUzLatn: "Qarshi tumani",
    nameRu: "Каршинский район",
    regionId: 10,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1710229,
    name: "Kasansky district",
    nameUzCyrl: "Косон тумани",
    nameUzLatn: "Koson tumani",
    nameRu: "Касанский район",
    regionId: 10,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1710232,
    name: "Kitab district",
    nameUzCyrl: "Китоб тумани",
    nameUzLatn: "Kitob tumani",
    nameRu: "Китабский район",
    regionId: 10,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1710233,
    name: "Mirishkor district",
    nameUzCyrl: "Миришкор тумани",
    nameUzLatn: "Mirishkor tumani",
    nameRu: "Миришкорский район",
    regionId: 10,
    districtsId: 17,
    active: 1,
  },
  {
    code: 1710234,
    name: "Mubarek region",
    nameUzCyrl: "Муборак тумани",
    nameUzLatn: "Muborak tumani",
    nameRu: "Мубарекский район",
    regionId: 10,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1710235,
    name: "Nishan district",
    nameUzCyrl: "Нишон тумани",
    nameUzLatn: "Nishon tumani",
    nameRu: "Нишанский район",
    regionId: 10,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1710237,
    name: "Kasbinsky district",
    nameUzCyrl: "Касби тумани",
    nameUzLatn: "Kasbi tumani",
    nameRu: "Касбинский район",
    regionId: 10,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1710242,
    name: "Chirakchi region",
    nameUzCyrl: "Чироқчи тумани",
    nameUzLatn: "Chiroqchi tumani",
    nameRu: "Чиракчинский район",
    regionId: 10,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1710245,
    name: "Shakhrisabz district",
    nameUzCyrl: "Шаҳрисабз тумани",
    nameUzLatn: "Shahrisabz tumani",
    nameRu: "Шахрисабзский район",
    regionId: 10,
    districtsId: 15,
    active: 1,
  },
  {
    code: 1710250,
    name: "Yakkabag district",
    nameUzCyrl: "Яккабоғ тумани",
    nameUzLatn: "Yakkabog' tumani",
    nameRu: "Яккабагский район",
    regionId: 10,
    districtsId: 16,
    active: 1,
  },
  {
    code: 1710401,
    name: "Karshi",
    nameUzCyrl: "Қарши шаҳар",
    nameUzLatn: "Qarshi shahar",
    nameRu: "город Карши",
    regionId: 10,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1710405,
    name: "Shakhrisabz",
    nameUzCyrl: "Шаҳрисабз шаҳар",
    nameUzLatn: "Shahrisabz shahar",
    nameRu: "город Шахрисабз",
    regionId: 10,
    districtsId: 2,
    active: 1,
  },
  {
    code: 1710240,
    name: "Ko'kdala tumani",
    nameUzCyrl: "Кўкдала тумани",
    nameUzLatn: "Ko'kdala tumani",
    nameRu: "Кокдалинский район",
    regionId: 10,
    districtsId: 18,
    active: 1,
  },

  {
    code: 1712211,
    name: "Kanimekhsky district",
    nameUzCyrl: "Конимех тумани",
    nameUzLatn: "Konimex tumani",
    nameRu: "Канимехский район",
    regionId: 12,
    districtsId: 4,
    active: 1,
  },
  {
    code: 1712216,
    name: "Kyzyltepa region",
    nameUzCyrl: "Қизилтепа тумани",
    nameUzLatn: "Qiziltepa tumani",
    nameRu: "Кызылтепинский район",
    regionId: 12,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1712230,
    name: "Navbakhor region",
    nameUzCyrl: "Навбаҳор тумани",
    nameUzLatn: "Navbahor tumani",
    nameRu: "Навбахорский район",
    regionId: 12,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1712234,
    name: "Karmaninsky district",
    nameUzCyrl: "Кармана тумани",
    nameUzLatn: "Karmana tumani",
    nameRu: "Карманинский район",
    regionId: 12,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1712238,
    name: "Nurata district",
    nameUzCyrl: "Нурота тумани",
    nameUzLatn: "Nurota tumani",
    nameRu: "Нуратинский район",
    regionId: 12,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1712244,
    name: "Tamdynsky district",
    nameUzCyrl: "Томди тумани",
    nameUzLatn: "Tomdi tumani",
    nameRu: "Тамдынский район",
    regionId: 12,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1712248,
    name: "Uchkuduk district",
    nameUzCyrl: "Учкудуқ шаҳар",
    nameUzLatn: "Uchkuduq shahar",
    nameRu: "город Учкудук",
    regionId: 12,
    districtsId: 3,
    active: 1,
  },
  {
    code: 1712251,
    name: "Khatyrchinsky district",
    nameUzCyrl: "Хатирчи тумани",
    nameUzLatn: "Xatirchi tumani",
    nameRu: "Хатырчинский район",
    regionId: 12,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1712401,
    name: "Navoi",
    nameUzCyrl: "Навоий шаҳар",
    nameUzLatn: "Navoiy shahar",
    nameRu: "город Навойи",
    regionId: 12,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1712408,
    name: "Zarafshan",
    nameUzCyrl: "Зарафшон шаҳар",
    nameUzLatn: "Zarafshon shahar",
    nameRu: "город Зарафшан",
    regionId: 12,
    districtsId: 2,
    active: 1,
  },
  {
    code: 1712412,
    name: "Gazgan",
    nameUzCyrl: "Ғозғон шаҳар",
    nameUzLatn: "G‘ozg‘on shahar",
    nameRu: "город Газган",
    regionId: 12,
    districtsId: 13,
    active: 1,
  },

  {
    code: 1708215,
    name: "Dustlik district",
    nameUzCyrl: "Дўстлик тумани",
    nameUzLatn: "Do'stlik tumani",
    nameRu: "Дустликский район",
    regionId: 8,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1708218,
    name: "Zaamin district",
    nameUzCyrl: "Зомин тумани",
    nameUzLatn: "Zomin tumani",
    nameRu: "Зааминский район",
    regionId: 8,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1708220,
    name: "Zarbdar region",
    nameUzCyrl: "Зарбдор тумани",
    nameUzLatn: "Zarbdor tumani",
    nameRu: "Зарбдарский район",
    regionId: 8,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1708223,
    name: "Mirzachul district",
    nameUzCyrl: "Мирзачўл тумани",
    nameUzLatn: "Mirzacho'l tumani",
    nameRu: "Мирзачульский район",
    regionId: 8,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1708225,
    name: "Zafarabad district",
    nameUzCyrl: "Зафаробод тумани",
    nameUzLatn: "Zafarobod tumani",
    nameRu: "Зафарабадский район",
    regionId: 8,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1708228,
    name: "Pakhtakor district",
    nameUzCyrl: "Пахтакор тумани",
    nameUzLatn: "Paxtakor tumani",
    nameRu: "Пахтакорский район",
    regionId: 8,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1708235,
    name: "Farish district",
    nameUzCyrl: "Фориш тумани",
    nameUzLatn: "Forish tumani",
    nameRu: "Фаришский район",
    regionId: 8,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1708237,
    name: "Yangiobodsky district",
    nameUzCyrl: "Янгиобод тумани",
    nameUzLatn: "Yangiobod tumani",
    nameRu: "Янгиободский район",
    regionId: 8,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1708401,
    name: "Jizzakh",
    nameUzCyrl: "Жиззах шаҳар",
    nameUzLatn: "Jizzax shahar",
    nameRu: "город Джизак",
    regionId: 8,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1708201,
    name: "Arnasay district",
    nameUzCyrl: "Арнасой тумани",
    nameUzLatn: "Arnasoy tumani",
    nameRu: "Арнасайский район",
    regionId: 8,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1708204,
    name: "Bakhmal region",
    nameUzCyrl: "Бахмал тумани",
    nameUzLatn: "Baxmal tumani",
    nameRu: "Бахмальский район",
    regionId: 8,
    districtsId: 2,
    active: 1,
  },
  {
    code: 1708209,
    name: "Gallaaral district",
    nameUzCyrl: "Ғаллаорол тумани",
    nameUzLatn: "G'allaorol tumani",
    nameRu: "Галляаральский район",
    regionId: 8,
    districtsId: 3,
    active: 1,
  },
  {
    code: 1708212,
    name: "Sharof Rashidov district",
    nameUzCyrl: "Шароф Рашидов тумани",
    nameUzLatn: "Sharof Rashidov tumani",
    nameRu: "Шароф Рашидовский район",
    regionId: 8,
    districtsId: 4,
    active: 1,
  },

  {
    code: 1718203,
    name: "Akdarya region",
    nameUzCyrl: "Оқдарё тумани",
    nameUzLatn: "Oqdaryo tumani",
    nameRu: "Акдарьинский район",
    regionId: 18,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1718206,
    name: "Bulungur district",
    nameUzCyrl: "Булунғур тумани",
    nameUzLatn: "Bulung'ur tumani",
    nameRu: "Булунгурский район",
    regionId: 18,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1718209,
    name: "Jambay region",
    nameUzCyrl: "Жомбой тумани",
    nameUzLatn: "Jomboy tumani",
    nameRu: "Джамбайский район",
    regionId: 18,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1718236,
    name: "Urgut district",
    nameUzCyrl: "Ургут тумани",
    nameUzLatn: "Urgut tumani",
    nameRu: "Ургутский район",
    regionId: 18,
    districtsId: 22,
    active: 1,
  },
  {
    code: 1718238,
    name: "Taylyak district",
    nameUzCyrl: "Тайлоқ тумани",
    nameUzLatn: "Tayloq tumani",
    nameRu: "Тайлякский район",
    regionId: 18,
    districtsId: 4,
    active: 1,
  },
  {
    code: 1718401,
    name: "Samarkand",
    nameUzCyrl: "Самарқанд шаҳар",
    nameUzLatn: "Samarqand shahar",
    nameRu: "город Самарканд",
    regionId: 18,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1718406,
    name: "Kattakurgan",
    nameUzCyrl: "Каттақўрғон шаҳар",
    nameUzLatn: "Kattaqo‘rg‘on shahar",
    nameRu: "город Каттакурган",
    regionId: 18,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1718212,
    name: "Ishtykhan district",
    nameUzCyrl: "Иштихон тумани",
    nameUzLatn: "Ishtixon tumani",
    nameRu: "Иштыханский район",
    regionId: 18,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1718215,
    name: "Kattakurgan region",
    nameUzCyrl: "Каттақўрғон тумани",
    nameUzLatn: "Kattaqo'rg'on tumani",
    nameRu: "Каттакурганский район",
    regionId: 18,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1718216,
    name: "Koshrabad district",
    nameUzCyrl: "Қўшработ тумани",
    nameUzLatn: "Qo'shrabot tumani",
    nameRu: "Кошрабадский район",
    regionId: 18,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1718218,
    name: "Narpay district",
    nameUzCyrl: "Нарпай тумани",
    nameUzLatn: "Narpay tumani",
    nameRu: "Нарпайский район",
    regionId: 18,
    districtsId: 15,
    active: 1,
  },
  {
    code: 1718224,
    name: "Payaryk district",
    nameUzCyrl: "Паяриқ тумани",
    nameUzLatn: "Payariq tumani",
    nameRu: "Пайарыкский район",
    regionId: 18,
    districtsId: 17,
    active: 1,
  },
  {
    code: 1718227,
    name: "Pastdargom district",
    nameUzCyrl: "Пастдарғом тумани",
    nameUzLatn: "Pastdarg'om tumani",
    nameRu: "Пастдаргомский район",
    regionId: 18,
    districtsId: 18,
    active: 1,
  },
  {
    code: 1718230,
    name: "Pakhtachi district",
    nameUzCyrl: "Пахтачи тумани",
    nameUzLatn: "Paxtachi tumani",
    nameRu: "Пахтачийский район",
    regionId: 18,
    districtsId: 19,
    active: 1,
  },
  {
    code: 1718233,
    name: "Samarkand region",
    nameUzCyrl: "Самарқанд тумани",
    nameUzLatn: "Samarqand tumani",
    nameRu: "Самаркандский район",
    regionId: 18,
    districtsId: 20,
    active: 1,
  },
  {
    code: 1718235,
    name: "Nurabad district",
    nameUzCyrl: "Нуробод тумани",
    nameUzLatn: "Nurobod tumani",
    nameRu: "Нурабадский район",
    regionId: 18,
    districtsId: 21,
    active: 1,
  },

  {
    code: 1722401,
    name: "Termez",
    nameUzCyrl: "Термиз шаҳар",
    nameUzLatn: "Termiz shahar",
    nameRu: "город Термез",
    regionId: 22,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1722220,
    name: "Termez district",
    nameUzCyrl: "Термиз тумани",
    nameUzLatn: "Termiz tumani",
    nameRu: "Термезский район",
    regionId: 22,
    districtsId: 12,
    active: 1,
  },
  {
    code: 1722221,
    name: "Uzun district",
    nameUzCyrl: "Узун тумани",
    nameUzLatn: "Uzun tumani",
    nameRu: "Узунский район",
    regionId: 22,
    districtsId: 15,
    active: 1,
  },
  {
    code: 1722223,
    name: "Sherabad region",
    nameUzCyrl: "Шеробод тумани",
    nameUzLatn: "Sherobod tumani",
    nameRu: "Шерабадский район",
    regionId: 22,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1722226,
    name: "Shurchinsky district",
    nameUzCyrl: "Шўрчи тумани",
    nameUzLatn: "Sho'rchi tumani",
    nameRu: "Шурчинский район",
    regionId: 22,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1722201,
    name: "Altynsay district",
    nameUzCyrl: "Олтинсой тумани",
    nameUzLatn: "Oltinsoy tumani",
    nameRu: "Алтынсайский район",
    regionId: 22,
    districtsId: 4,
    active: 1,
  },
  {
    code: 1722202,
    name: "Angora region",
    nameUzCyrl: "Ангор тумани",
    nameUzLatn: "Angor tumani",
    nameRu: "Ангорский район",
    regionId: 22,
    districtsId: 3,
    active: 1,
  },
  {
    code: 1722203,
    name: "Bandikhon district",
    nameUzCyrl: "Бандихон тумани",
    nameUzLatn: "Bandixon tumani",
    nameRu: "Бандихонский район",
    regionId: 22,
    districtsId: 16,
    active: 1,
  },
  {
    code: 1722204,
    name: "Baysun district",
    nameUzCyrl: "Бойсун тумани",
    nameUzLatn: "Boysun tumani",
    nameRu: "Байсунский район",
    regionId: 22,
    districtsId: 5,
    active: 1,
  },
  {
    code: 1722207,
    name: "Muzrabad district",
    nameUzCyrl: "Музработ тумани",
    nameUzLatn: "Muzrabot tumani",
    nameRu: "Музрабадский район",
    regionId: 22,
    districtsId: 6,
    active: 1,
  },
  {
    code: 1722210,
    name: "Denau district",
    nameUzCyrl: "Денов тумани",
    nameUzLatn: "Denov tumani",
    nameRu: "Денауский район",
    regionId: 22,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1722212,
    name: "Jarkurgan region",
    nameUzCyrl: "Жарқўрғон тумани",
    nameUzLatn: "Jarqo'rg'on tumani",
    nameRu: "Джаркурганский район",
    regionId: 22,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1722214,
    name: "Kumkurgan region",
    nameUzCyrl: "Қумқўрғон тумани",
    nameUzLatn: "Qumqo'rg'on tumani",
    nameRu: "Кумкурганский район",
    regionId: 22,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1722215,
    name: "Kizirik district",
    nameUzCyrl: "Қизириқ тумани",
    nameUzLatn: "Qiziriq tumani",
    nameRu: "Кизирикский район",
    regionId: 22,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1722217,
    name: "Sariasi region",
    nameUzCyrl: "Сариосиё тумани",
    nameUzLatn: "Sariosiyo tumani",
    nameRu: "Сариасийский район",
    regionId: 22,
    districtsId: 11,
    active: 1,
  },

  {
    code: 1714229,
    name: "Uychinsky district",
    nameUzCyrl: "Уйчи тумани",
    nameUzLatn: "Uychi tumani",
    nameRu: "Уйчинский район",
    regionId: 14,
    districtsId: 13,
    active: 1,
  },
  {
    code: 1714234,
    name: "Uchkurgan region",
    nameUzCyrl: "Учқўрғон тумани",
    nameUzLatn: "Uchqo'rg'on tumani",
    nameRu: "Учкурганский район",
    regionId: 14,
    districtsId: 14,
    active: 1,
  },
  {
    code: 1714236,
    name: "Chartak district",
    nameUzCyrl: "Чортоқ тумани",
    nameUzLatn: "Chortoq tumani",
    nameRu: "Чартакский район",
    regionId: 14,
    districtsId: 15,
    active: 1,
  },
  {
    code: 1714237,
    name: "Chust district",
    nameUzCyrl: "Чуст тумани",
    nameUzLatn: "Chust tumani",
    nameRu: "Чустский район",
    regionId: 14,
    districtsId: 16,
    active: 1,
  },
  {
    code: 1714242,
    name: "Yangikurgan region",
    nameUzCyrl: "Янгиқўрғон тумани",
    nameUzLatn: "Yangiqo'rg'on tumani",
    nameRu: "Янгикурганский район",
    regionId: 14,
    districtsId: 17,
    active: 1,
  },
  {
    code: 1714401,
    name: "Namangan",
    nameUzCyrl: "Наманган шаҳар",
    nameUzLatn: "Namangan shahar",
    nameRu: "город Наманган",
    regionId: 14,
    districtsId: 1,
    active: 1,
  },
  {
    code: 1714401360,
    name: "Yangi Namangan shaxri",
    nameUzCyrl: "Yangi Namangan shaxri",
    nameUzLatn: "Yangi Namangan shaxri",
    nameRu: "Районы города Наманган",
    regionId: 14,
    districtsId: 19,
    active: 1,
  },
  {
    code: 1714401365,
    name: "Davlatobod tumani",
    nameUzCyrl: "Davlatobod tumani",
    nameUzLatn: "Davlatobod tumani",
    nameRu: "Давлатободский район",
    regionId: 14,
    districtsId: 18,
    active: 1,
  },
  {
    code: 1714204,
    name: "Mingbulak district",
    nameUzCyrl: "Мингбулоқ тумани",
    nameUzLatn: "Mingbuloq tumani",
    nameRu: "Мингбулакский район",
    regionId: 14,
    districtsId: 7,
    active: 1,
  },
  {
    code: 1714207,
    name: "Kasansay district",
    nameUzCyrl: "Косонсой тумани",
    nameUzLatn: "Kosonsoy tumani",
    nameRu: "Касансайский район",
    regionId: 14,
    districtsId: 8,
    active: 1,
  },
  {
    code: 1714212,
    name: "Namangan region",
    nameUzCyrl: "Наманган тумани",
    nameUzLatn: "Namangan tumani",
    nameRu: "Наманганский район",
    regionId: 14,
    districtsId: 9,
    active: 1,
  },
  {
    code: 1714216,
    name: "Naryn region",
    nameUzCyrl: "Норин тумани",
    nameUzLatn: "Norin tumani",
    nameRu: "Нарынский район",
    regionId: 14,
    districtsId: 10,
    active: 1,
  },
  {
    code: 1714219,
    name: "Papal District",
    nameUzCyrl: "Поп тумани",
    nameUzLatn: "Pop tumani",
    nameRu: "Папский район",
    regionId: 14,
    districtsId: 11,
    active: 1,
  },
  {
    code: 1714224,
    name: "Turakurgan region",
    nameUzCyrl: "Тўрақўрғон тумани",
    nameUzLatn: "To'raqo'rg'on tumani",
    nameRu: "Туракурганский район",
    regionId: 14,
    districtsId: 12,
    active: 1,
  },

  {
    code: 1750001,
    name: "Yirik soliq to'lovchilar",
    nameUzCyrl: "Йирик солиқ тўловчилар",
    nameUzLatn: "Yirik soliq to'lovchilar",
    nameRu: "Крупные налогоплательщики",
    regionId: 50,
    districtsId: 1,
    active: 1,
  },
];
